### ISSUE TITLE
Add a Sitemap-friendly option

### ISSUE THREAD

**Issue by swarley7** [C-Sto/recursebuster#11]
Having the option to use recursebuster with Burp is very cool, but all of the failed / 404'd requests will very quickly clog up the sitemap when used with even the smallest of wordlists.

Could you add some logic to only forward requests that respond with a good status code (e.g. non-404) through the proxy.

I'm thinking something like a `-SitemapFriendly` flag, which will require the `Proxy` flag to be set, and then maybe performs the initial `HEAD` request directly (not via the proxy) and then depending on the response code/data send the followup `GET` request via the proxy.

**Comment by C-Sto** [comment]
Done in 1.0.13 - set the sitemap flag and it will use the configured proxy _only_ for confirmed 'good' requests. Will work in HEAD only mode too. Don't forget to disable intercept.
