### ISSUE TITLE
Mac Os

### ISSUE THREAD

**Issue by Teicu** [C-Sto/recursebuster#23]
Hello 

Can you explain please how it comes installed in Mac? 

thanks

**Comment by C-Sto** [comment]
I don't understand the question

**Comment by Teicu** [comment]
I.m sorry, I asked if you can explain better how can be installed on mac os

**Comment by C-Sto** [comment]
releases can be found in the releases section (https://github.com/C-Sto/recursebuster/releases)

Alternatively, if you have Go set up you should be able to just `go get -u github.com/c-sto/recursebuster`

**Comment by C-Sto** [comment]
Did this resolve your problem?

**Comment by Teicu** [comment]
Hi 

not really, as I said I'm using Mac os, I don't have go installed. So I don't know how to use it. I'm sorry

**Comment by C-Sto** [comment]
go to https://github.com/C-Sto/recursebuster/releases - download the mac version, then run it

**Comment by C-Sto** [comment]
Did this resolve your problem?

**Comment by Teicu** [comment]
No, I'm really sorry. 

I installed go in my Mac via brew. Then I installed recursebuster and when I try to use it I get "-bash: recursebuster: command not found" 

I also downloaded the mac version on my desktop and I'm not able to run it from terminal. So maybe I don't know how to run it correctly
 
So please close this thread as resolved because I'll give up. 

Thank you anyway.

**Comment by C-Sto** [comment]
You will need to add the go bin location to your path (`~/go/bin` usually). `export PATH=$PATH:~/go/bin`, then try `recursebuster` again.

**Comment by C-Sto** [comment]
closing as per request
